In [4]:
import numpy as np
grid = [ [3, 0, 6, 5, 0, 8, 4, 0, 0], 
         [5, 2, 0, 0, 0, 0, 0, 0, 0], 
         [0, 8, 7, 0, 0, 0, 0, 3, 1], 
         [0, 0, 3, 0, 1, 0, 0, 8, 0], 
         [9, 0, 0, 8, 6, 3, 0, 0, 5], 
         [0, 5, 0, 0, 9, 0, 6, 0, 0], 
         [1, 3, 0, 0, 0, 0, 2, 5, 0], 
         [0, 0, 0, 0, 0, 0, 0, 7, 4], 
         [0, 0, 5, 2, 0, 6, 3, 0, 0] ]
def ispossible(row,col,n):
    global grid
    for i in range(0,9):
        if grid[row][i]==n and col!=i:
            return False
    for i in range(0,9):
        if grid[i][col]==n and row!=i:
            return False
    x_box=row//3
    y_box=col//3
    for i in range(x_box*3,x_box*3+3):
        for j in range(y_box*3,y_box*3+3):
            if grid[i][j]==n and (i!=row and j!=col):
                return False
    return True
ispossible(3,4,5)
def findtheposition():
    global grid
    for i in range(0,9):
        for j in range(0,9):
            if grid[i][j]==0:
                for n in range(1,10):
                    #ROW NUMBER # COLUMN NUMBER # THE VALUE WHICH YOU NEED TO INSERT
                    if ispossible(i,j,n):
                        grid[i][j]=n
                        findtheposition()
                        grid[i][j]=0
                return
    print(np.matrix(grid))
findtheposition()

[[3 1 6 5 7 8 4 9 2]
 [5 2 9 1 3 4 7 6 8]
 [4 8 7 6 2 9 5 3 1]
 [2 6 3 4 1 5 9 8 7]
 [9 7 4 8 6 3 1 2 5]
 [8 5 1 7 9 2 6 4 3]
 [1 3 8 9 4 7 2 5 6]
 [6 9 2 3 5 1 8 7 4]
 [7 4 5 2 8 6 3 1 9]]
